FROM python:latest
WORKDIR /python-docker
COPY . /python-docker
RUN pip install -r requirements.txt
CMD [ "python" , "app.py" ]

# FROM python
# WORKDIR /app 
# COPY . /app 
# RUN pip install --no-cache-dir -r requirements.txt 
# CMD ["python", "app.py"] `


